version: "3"
 
services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    ports:
      - "8080:8081"
    build: .
    env_file:
      - .env
      - .app.db.env
      - .auth.env
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    restart: always
      